title: jjmean2의 Today I Learned 노트
author: Jongwan Lee
email: jongwan.lee325@gmail.com
description: >-
  개발에 대해 매일매일 배운 것을 정리하는 노트
baseurl: ""
url: "http://til.kaisys.xyz"
github_username: jjmean2
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
permalink: /:year/:month/:day/:title
disqus:
  shortname: jjmean2-til
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true
